apiVersion: v2
name: hello-world
description: A Helm chart for Kubernetes

type: application

version: 1.0.0

appVersion: "1.0.0"

dependencies:
  - name: mysql
    ## Update not supported by dependabot
    version: 8.0.26
    repository: https://charts.bitnami.com/bitnami
